# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivet < Formula
  desc "Interactive TUI for browsing and managing GitHub Actions workflows"
  homepage "https://github.com/cloudsky01/gh-rivet"
  version "0.3.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v0.3.10/gh-rivet_0.3.10_Darwin_x86_64.tar.gz"
      sha256 "9d32dff82c13dcd70454329c4e035f4fa6553a8e6e69e1cd5dbc48e5058b8f8f"

      def install
        bin.install "rivet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v0.3.10/gh-rivet_0.3.10_Darwin_arm64.tar.gz"
      sha256 "8c0ba2477bbbd42ec2bc50b8135601bedddc8aaa07ca148f4e5d2fe0ed4738ce"

      def install
        bin.install "rivet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v0.3.10/gh-rivet_0.3.10_Linux_x86_64.tar.gz"
      sha256 "269e9d597388cfb3c71b41b127619fa99c121168e092d22f5413ed93ead0f52e"
      def install
        bin.install "rivet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v0.3.10/gh-rivet_0.3.10_Linux_arm64.tar.gz"
      sha256 "787b4c726638fcf46b6da7da237a1d476e8f8589add001757d4cd9f10f5c1a56"
      def install
        bin.install "rivet"
      end
    end
  end
end
