# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivet < Formula
  desc "Interactive TUI for browsing and managing GitHub Actions workflows"
  homepage "https://github.com/cloudsky01/gh-rivet"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v1.0.3/gh-rivet_1.0.3_Darwin_x86_64.tar.gz"
      sha256 "88e0cf045f4aeba753596b06a6b265908189012b044a79b4cf8bb2b2d949a97d"

      def install
        bin.install "rivet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v1.0.3/gh-rivet_1.0.3_Darwin_arm64.tar.gz"
      sha256 "9c5455785a63a4a808776390f11016de6302b90a868836baba71f949fde8f941"

      def install
        bin.install "rivet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v1.0.3/gh-rivet_1.0.3_Linux_x86_64.tar.gz"
      sha256 "3b126952ea0f5b648ac4ba504f4cddafba5d44d2b9829c0615f7e1b3a7edf28c"
      def install
        bin.install "rivet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudsky01/gh-rivet/releases/download/v1.0.3/gh-rivet_1.0.3_Linux_arm64.tar.gz"
      sha256 "0a6e2570352aa6b3c03096f00459eda027945af7bc152253e9dd2c31ad6e6c77"
      def install
        bin.install "rivet"
      end
    end
  end
end
